################################################################################

# Helpers

@address = http://localhost:4096/fanaro-firebase-lab/southamerica-east1/goBrasilRanking

## Home Test

### GET
GET {{address}}

################################################################################

# Players

## GET

### Players Max

GET {{address}}/jogadores

### Player by ID

@fakeId1 = 0

GET {{address}}/jogadores/{{fakeId1}}

### Player Exists by ID

@fakeId2 = 0

GET {{address}}/jogadores/{{fakeId2}}?existe

## POST

### POST Player

POST {{address}}/jogadores/novo
content-type: application/json

{
    "name": "Philippe Fanaro",
    "countries": [
        {
            "name": "Brazil",
            "state": "SP",
            "city": "São Paulo"
        }
    ],
    "elo": 2100
}
################################################################################

## Game Events

### 1. GET All

GET {{address}}/partidas

### 2. GET

GET {{address}}/partidas/0

### 3. POST

POST {{address}}/partidas/novo

################################################################################

## Game Records

### 1. GET All

GET {{address}}/partidas?de=0

### 2. GET

GET {{address}}/partidas/0

### 2.1. GET game records from player

GET {{address}}/partidas?jogadorRef=0

### 3. POST

GET {{address}}/partidas/novo
content-type: application/json

{
    
}

### 4. GET games by player

GET {{address}}/partidas?jogadorRef=0

################################################################################

## Mock

### 1. Mock Populate Players

POST {{address}}/jogadores/mock-populate

### 2. Mock Populate Game Events

POST {{address}}/eventos/mock-populate

### 3. Mock Populate Game Records

POST {{address}}/partidas/mock-populate

### 4. Mock Populate Everything

POST {{address}}/mock-populate-everything

### GET Players

GET {{address}}/jogadores?de=0&somenteBrasileiros=true

################################################################################

## Other Stuff

### 1. Graph Data

@game=10

GET {{address}}/partidas/{{game}}?data-elo=true

################################################################################

# Real Function

@addressReal = https://southamerica-east1-fanaro-firebase-lab.cloudfunctions.net/goBrasilRanking

### Test

GET {{addressReal}}

### Mock Real

POST {{addressReal}}/mock-populate-everything

## Create Indices on Firebase

### GET Players

GET {{addressReal}}/jogadores?de=0&somenteBrasileiros=true

### GET Game Records / Date Elo

GET {{addressReal}}/partidas?data-elo=true&jogadorRef1=54

### GET Game Records / Player 1 and 2

GET {{addressReal}}/partidas?de=0&jogadorRef1=53&jogadoreRef2=44

### GET Game Records / EventRef

GET {{addressReal}}/partidas?de=0&eventoRef=6

################################################################################